#!/usr/bin/php
<?php

list($file, $xpath) = array_slice($argv, 1, 3);

$dom = new DOMDocument();
$dom->load($file);

$domx = new DOMXPath($dom);
$entries = $domx->query($xpath);

foreach($entries as $entry) {
	
	switch(true) {
		case ($entry instanceof DOMText): {
			$text = 'wholeText';
		}
		break;
		case ($entry instanceof DOMNode): {
			$text = 'nodeValue';
		}
		break;
	}

	print($entry->$text . PHP_EOL );	

}

